services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Speeray-mdb-8391
      MARIADB_DATABASE: multitool_db_prod
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin-123
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  multitoolapi:
    build: 
      context: ./MultitoolAPI
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db

  multitool-frontend:
    build:
      context: ./Multitool-Frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "8000:80"
    depends_on:
      - multitoolapi

volumes:
  dbdata:
