// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultitoolApi.ConfigModels;

#nullable disable

namespace MultitoolApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250714165728_AddRowPositionToCustomRow")]
    partial class AddRowPositionToCustomRow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MultitoolApi.Businesslogic.Models.CalendarEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("eventId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("endDateTime");

                    b.Property<string>("EventNote")
                        .HasColumnType("longtext")
                        .HasColumnName("eventNote");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("eventTitle");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isAllDay");

                    b.Property<DateTime?>("RecurrenceEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recurrenceEnd");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("longtext")
                        .HasColumnName("recurrenceRule");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("startDateTime");

                    b.HasKey("EventId");

                    b.HasIndex("CategoryId");

                    b.ToTable("calendar_events", (string)null);
                });

            modelBuilder.Entity("MultitoolApi.Businesslogic.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("categoryName");

                    b.HasKey("CategoryId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("MultitoolApi.Infrastructure.DataAccessLayer.Models.CustomTable.CustomCell", b =>
                {
                    b.Property<long>("RowId")
                        .HasColumnType("bigint");

                    b.Property<long>("ColumnId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("ValBool")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("val_bool");

                    b.Property<DateTime?>("ValDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("val_date");

                    b.Property<decimal?>("ValDec")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("val_dec");

                    b.Property<long?>("ValInt")
                        .HasColumnType("bigint")
                        .HasColumnName("val_int");

                    b.Property<string>("ValString")
                        .HasColumnType("longtext")
                        .HasColumnName("val_string");

                    b.HasKey("RowId", "ColumnId");

                    b.HasIndex("ColumnId", "ValDate")
                        .HasDatabaseName("idx_cell_date");

                    b.HasIndex("ColumnId", "ValDec")
                        .HasDatabaseName("idx_cell_dec");

                    b.HasIndex("ColumnId", "ValInt")
                        .HasDatabaseName("idx_cell_int");

                    b.ToTable("custom_cell", (string)null);
                });

            modelBuilder.Entity("MultitoolApi.Infrastructure.DataAccessLayer.Models.CustomTable.CustomColumn", b =>
                {
                    b.Property<long>("ColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ColumnId"));

                    b.Property<int>("ColOrder")
                        .HasColumnType("int")
                        .HasColumnName("col_order");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("enum('string','int','decimal','date','bool')")
                        .HasColumnName("data_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<long>("TableId")
                        .HasColumnType("bigint");

                    b.HasKey("ColumnId");

                    b.HasIndex("TableId");

                    b.ToTable("custom_column", (string)null);
                });

            modelBuilder.Entity("MultitoolApi.Infrastructure.DataAccessLayer.Models.CustomTable.CustomRow", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("RowOrder")
                        .HasColumnType("int");

                    b.Property<long>("TableId")
                        .HasColumnType("bigint");

                    b.HasKey("RowId");

                    b.HasIndex("TableId");

                    b.ToTable("custom_row", (string)null);
                });

            modelBuilder.Entity("MultitoolApi.Infrastructure.DataAccessLayer.Models.CustomTable.CustomTable", b =>
                {
                    b.Property<long>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tableId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("TableId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("tableName");

                    b.HasKey("TableId");

                    b.ToTable("custom_table", (string)null);
                });

            modelBuilder.Entity("MultitoolApi.Businesslogic.Models.CalendarEvent", b =>
                {
                    b.HasOne("MultitoolApi.Businesslogic.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_calendar_events_categoryId");
                });

            modelBuilder.Entity("MultitoolApi.Infrastructure.DataAccessLayer.Models.CustomTable.CustomCell", b =>
                {
                    b.HasOne("MultitoolApi.Infrastructure.DataAccessLayer.Models.CustomTable.CustomColumn", "Column")
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MultitoolApi.Infrastructure.DataAccessLayer.Models.CustomTable.CustomRow", "Row")
                        .WithMany("Cells")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("MultitoolApi.Infrastructure.DataAccessLayer.Models.CustomTable.CustomColumn", b =>
                {
                    b.HasOne("MultitoolApi.Infrastructure.DataAccessLayer.Models.CustomTable.CustomTable", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("MultitoolApi.Infrastructure.DataAccessLayer.Models.CustomTable.CustomRow", b =>
                {
                    b.HasOne("MultitoolApi.Infrastructure.DataAccessLayer.Models.CustomTable.CustomTable", "Table")
                        .WithMany("Rows")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("MultitoolApi.Infrastructure.DataAccessLayer.Models.CustomTable.CustomRow", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("MultitoolApi.Infrastructure.DataAccessLayer.Models.CustomTable.CustomTable", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
