// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultitoolApi.ConfigModels;

#nullable disable

namespace MultitoolApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MultitoolApi.Businesslogic.Models.CalendarEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("eventId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("endDateTime");

                    b.Property<string>("EventNote")
                        .HasColumnType("longtext")
                        .HasColumnName("eventNote");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("eventTitle");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isAllDay");

                    b.Property<DateTime?>("RecurrenceEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recurrenceEnd");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("longtext")
                        .HasColumnName("recurrenceRule");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("startDateTime");

                    b.HasKey("EventId");

                    b.HasIndex("CategoryId");

                    b.ToTable("calendar_events", (string)null);
                });

            modelBuilder.Entity("MultitoolApi.Businesslogic.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("categoryName");

                    b.HasKey("CategoryId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("MultitoolApi.Businesslogic.Models.CalendarEvent", b =>
                {
                    b.HasOne("MultitoolApi.Businesslogic.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_calendar_events_categoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
