// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Multitool.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Multitool.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602102818_AddUserLockoutFields")]
    partial class AddUserLockoutFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Multitool.Domain.Entities.Calendar.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date_time");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_all_day");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("event_note");

                    b.Property<DateTime?>("RecurrenceEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recurrence_end");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("text")
                        .HasColumnName("recurrence_rule");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_title");

                    b.HasKey("Id")
                        .HasName("pk_calendar_events");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_calendar_events_category_id");

                    b.ToTable("calendar_events", (string)null);
                });

            modelBuilder.Entity("Multitool.Domain.Entities.Calendar.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Multitool.Domain.Entities.Config.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Cell", b =>
                {
                    b.Property<long>("RowId")
                        .HasColumnType("bigint")
                        .HasColumnName("row_id");

                    b.Property<long>("ColumnId")
                        .HasColumnType("bigint")
                        .HasColumnName("column_id");

                    b.Property<bool?>("ValBool")
                        .HasColumnType("boolean")
                        .HasColumnName("val_bool");

                    b.Property<DateTime?>("ValDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("val_date");

                    b.Property<decimal?>("ValDec")
                        .HasColumnType("numeric")
                        .HasColumnName("val_dec");

                    b.Property<long?>("ValInt")
                        .HasColumnType("bigint")
                        .HasColumnName("val_int");

                    b.Property<string>("ValString")
                        .HasColumnType("text")
                        .HasColumnName("val_string");

                    b.HasKey("RowId", "ColumnId")
                        .HasName("pk_custom_cells");

                    b.HasIndex("ColumnId", "ValDate")
                        .HasDatabaseName("idx_cell_date");

                    b.HasIndex("ColumnId", "ValDec")
                        .HasDatabaseName("idx_cell_dec");

                    b.HasIndex("ColumnId", "ValInt")
                        .HasDatabaseName("idx_cell_int");

                    b.ToTable("custom_cells", (string)null);
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Column", b =>
                {
                    b.Property<long>("ColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("column_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ColumnId"));

                    b.Property<int>("ColOrder")
                        .HasColumnType("integer")
                        .HasColumnName("col_order");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<long>("TableId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_id");

                    b.HasKey("ColumnId")
                        .HasName("pk_custom_columns");

                    b.HasIndex("TableId")
                        .HasDatabaseName("ix_custom_columns_table_id");

                    b.ToTable("custom_columns", (string)null);
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Row", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("RowOrder")
                        .HasColumnType("integer")
                        .HasColumnName("row_order");

                    b.Property<long>("TableId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_id");

                    b.HasKey("RowId")
                        .HasName("pk_custom_rows");

                    b.HasIndex("TableId")
                        .HasDatabaseName("ix_custom_rows_table_id");

                    b.ToTable("custom_rows", (string)null);
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Table", b =>
                {
                    b.Property<long>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("table_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TableId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("table_name");

                    b.HasKey("TableId")
                        .HasName("pk_custom_tables");

                    b.ToTable("custom_tables", (string)null);
                });

            modelBuilder.Entity("Multitool.Domain.Entities.Calendar.CalendarEvent", b =>
                {
                    b.HasOne("Multitool.Domain.Entities.Calendar.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_events_category_id");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Cell", b =>
                {
                    b.HasOne("Multitool.Domain.Entities.CustomTable.Column", "Column")
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_cells_custom_columns_column_id");

                    b.HasOne("Multitool.Domain.Entities.CustomTable.Row", "Row")
                        .WithMany("Cells")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_cells_custom_rows_row_id");

                    b.Navigation("Column");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Column", b =>
                {
                    b.HasOne("Multitool.Domain.Entities.CustomTable.Table", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_columns_custom_tables_table_id");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Row", b =>
                {
                    b.HasOne("Multitool.Domain.Entities.CustomTable.Table", "Table")
                        .WithMany("Rows")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_rows_custom_tables_table_id");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Row", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Table", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
