// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Multitool.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Multitool.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Multitool.Domain.Entities.Calendar.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date_time");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_all_day");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("event_note");

                    b.Property<DateTime?>("RecurrenceEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("recurrence_end");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("text")
                        .HasColumnName("recurrence_rule");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_title");

                    b.HasKey("Id")
                        .HasName("pk_calendar_events");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_calendar_events_category_id");

                    b.ToTable("calendar_events", "public");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.Category.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", "public");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.Config.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Cell", b =>
                {
                    b.Property<long>("RowId")
                        .HasColumnType("bigint")
                        .HasColumnName("row_id");

                    b.Property<long>("ColumnId")
                        .HasColumnType("bigint")
                        .HasColumnName("column_id");

                    b.Property<bool?>("ValBool")
                        .HasColumnType("boolean")
                        .HasColumnName("val_bool");

                    b.Property<DateTime?>("ValDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("val_date");

                    b.Property<decimal?>("ValDec")
                        .HasColumnType("numeric")
                        .HasColumnName("val_dec");

                    b.Property<long?>("ValInt")
                        .HasColumnType("bigint")
                        .HasColumnName("val_int");

                    b.Property<string>("ValString")
                        .HasColumnType("text")
                        .HasColumnName("val_string");

                    b.HasKey("RowId", "ColumnId")
                        .HasName("pk_cells");

                    b.HasIndex("ColumnId", "ValDate")
                        .HasDatabaseName("idx_cell_date");

                    b.HasIndex("ColumnId", "ValDec")
                        .HasDatabaseName("idx_cell_dec");

                    b.HasIndex("ColumnId", "ValInt")
                        .HasDatabaseName("idx_cell_int");

                    b.ToTable("cells", "custom");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Column", b =>
                {
                    b.Property<long>("ColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("column_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ColumnId"));

                    b.Property<int>("ColOrder")
                        .HasColumnType("integer")
                        .HasColumnName("col_order");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<long>("TableId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_id");

                    b.HasKey("ColumnId")
                        .HasName("pk_columns");

                    b.HasIndex("TableId")
                        .HasDatabaseName("ix_columns_table_id");

                    b.ToTable("columns", "custom");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Row", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("RowOrder")
                        .HasColumnType("integer")
                        .HasColumnName("row_order");

                    b.Property<long>("TableId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_id");

                    b.HasKey("RowId")
                        .HasName("pk_rows");

                    b.HasIndex("TableId")
                        .HasDatabaseName("ix_rows_table_id");

                    b.ToTable("rows", "custom");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Table", b =>
                {
                    b.Property<long>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("table_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TableId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("table_name");

                    b.HasKey("TableId")
                        .HasName("pk_tables");

                    b.ToTable("tables", "custom");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.Todo.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("todo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CompletedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed_date_time");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_date_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("todo_description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_done");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("todo_title");

                    b.HasKey("Id")
                        .HasName("pk_todos");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_todos_category_id");

                    b.ToTable("todos", "public");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.WorkTimePlanner.WeekSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("week_summary_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TotalOvertime")
                        .HasColumnType("integer")
                        .HasColumnName("total_overtime");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("week_number");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_week_summaries");

                    b.HasIndex("Year", "WeekNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_week_summaries_year_week");

                    b.ToTable("week_summaries", "worktime");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.WorkTimePlanner.WorkDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("work_day_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("break_minutes");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsHomeOffice")
                        .HasColumnType("boolean")
                        .HasColumnName("is_home_office");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<int>("OvertimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("overtime_minutes");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("WorkMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("work_minutes");

                    b.HasKey("Id")
                        .HasName("pk_work_days");

                    b.ToTable("work_days", "worktime");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.WorkTimePlanner.WorkTimeSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("settings_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BreakRule6h")
                        .HasColumnType("integer")
                        .HasColumnName("break_rule_6h");

                    b.Property<int>("BreakRule9h")
                        .HasColumnType("integer")
                        .HasColumnName("break_rule_9h");

                    b.Property<int>("DailyTargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("daily_target_minutes");

                    b.Property<int>("HomeOfficeLimit")
                        .HasColumnType("integer")
                        .HasColumnName("home_office_limit");

                    b.HasKey("Id")
                        .HasName("pk_work_time_settings");

                    b.ToTable("work_time_settings", "worktime");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.Calendar.CalendarEvent", b =>
                {
                    b.HasOne("Multitool.Domain.Entities.Category.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_events_category_id");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Cell", b =>
                {
                    b.HasOne("Multitool.Domain.Entities.CustomTable.Column", "Column")
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_cells_column_id");

                    b.HasOne("Multitool.Domain.Entities.CustomTable.Row", "Row")
                        .WithMany("Cells")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_cells_row_id");

                    b.Navigation("Column");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Column", b =>
                {
                    b.HasOne("Multitool.Domain.Entities.CustomTable.Table", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_columns_table_id");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Row", b =>
                {
                    b.HasOne("Multitool.Domain.Entities.CustomTable.Table", "Table")
                        .WithMany("Rows")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_rows_table_id");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.Todo.Todo", b =>
                {
                    b.HasOne("Multitool.Domain.Entities.Category.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todos_category_id");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Row", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Table", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
