// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Multitool.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Multitool.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Multitool.Domain.Entities.Calendar.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("eventId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("categoryId");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("endDateTime");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean")
                        .HasColumnName("isAllDay");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("eventNote");

                    b.Property<DateTime?>("RecurrenceEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recurrenceEnd");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("text")
                        .HasColumnName("recurrenceRule");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startDateTime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("eventTitle");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("calendar_events", (string)null);
                });

            modelBuilder.Entity("Multitool.Domain.Entities.Calendar.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("categoryId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoryName");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Cell", b =>
                {
                    b.Property<long>("RowId")
                        .HasColumnType("bigint");

                    b.Property<long>("ColumnId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("ValBool")
                        .HasColumnType("boolean")
                        .HasColumnName("val_bool");

                    b.Property<DateTime?>("ValDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("val_date");

                    b.Property<decimal?>("ValDec")
                        .HasColumnType("numeric")
                        .HasColumnName("val_dec");

                    b.Property<long?>("ValInt")
                        .HasColumnType("bigint")
                        .HasColumnName("val_int");

                    b.Property<string>("ValString")
                        .HasColumnType("text")
                        .HasColumnName("val_string");

                    b.HasKey("RowId", "ColumnId");

                    b.HasIndex("ColumnId", "ValDate")
                        .HasDatabaseName("idx_cell_date");

                    b.HasIndex("ColumnId", "ValDec")
                        .HasDatabaseName("idx_cell_dec");

                    b.HasIndex("ColumnId", "ValInt")
                        .HasDatabaseName("idx_cell_int");

                    b.ToTable("custom_cell", (string)null);
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Column", b =>
                {
                    b.Property<long>("ColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ColumnId"));

                    b.Property<int>("ColOrder")
                        .HasColumnType("integer")
                        .HasColumnName("col_order");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<long>("TableId")
                        .HasColumnType("bigint");

                    b.HasKey("ColumnId");

                    b.HasIndex("TableId");

                    b.ToTable("custom_column", (string)null);
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Row", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("RowOrder")
                        .HasColumnType("integer");

                    b.Property<long>("TableId")
                        .HasColumnType("bigint");

                    b.HasKey("RowId");

                    b.HasIndex("TableId");

                    b.ToTable("custom_row", (string)null);
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Table", b =>
                {
                    b.Property<long>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tableId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TableId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tableName");

                    b.HasKey("TableId");

                    b.ToTable("custom_table", (string)null);
                });

            modelBuilder.Entity("Multitool.Domain.Entities.Calendar.CalendarEvent", b =>
                {
                    b.HasOne("Multitool.Domain.Entities.Calendar.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_calendar_events_categoryId");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Cell", b =>
                {
                    b.HasOne("Multitool.Domain.Entities.CustomTable.Column", "Column")
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multitool.Domain.Entities.CustomTable.Row", "Row")
                        .WithMany("Cells")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Column", b =>
                {
                    b.HasOne("Multitool.Domain.Entities.CustomTable.Table", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Row", b =>
                {
                    b.HasOne("Multitool.Domain.Entities.CustomTable.Table", "Table")
                        .WithMany("Rows")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Row", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("Multitool.Domain.Entities.CustomTable.Table", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
