name: Build and Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  multitool-api:
    name: Build and Test .NET API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Multitool.sln

      - name: Build
        run: dotnet build ./Multitool.sln --configuration Release --no-restore

      - name: Test API
        run: dotnet test tests/Multitool.Api.Tests/Multitool.Api.Tests.csproj --configuration Release --no-build --verbosity normal

      - name: Test Application
        run: dotnet test tests/Multitool.Application.Tests/Multitool.Application.Tests.csproj --configuration Release --no-build --verbosity normal
      